### ISSUE TITLE
having issues seting up with klipper v0.10.0-526-ga151aa8c

### ISSUE THREAD

**Issue by invidtiv** [falo2k/klipper_neopixel_utility#2]
I m unable to setup.
I change section to neopixel_utiliy my_neopixels
and get  Section 'neopixel_utiliy my_neopixels' is not a valid config section.

in moonraker I get 
neopixel_utility
v0.1-8-g29b01f9
invalid and recover fails

not sure if this compatible with recent klipper v0.10.0-526-ga151aa8c

**Comment by falo2k** [comment]
It's not been touched for a while - pretty sure an update a few versions ago broke compatibility unfortunately, and this was never properly released.  The error you're getting is actually a typo in your config (which is also in my README) for the word "utility".

I'm pretty sure I saw another module out in the wild that added better neopixel stuff, but I haven't tried it myself.

Here it is: https://github.com/julianschill/klipper-led_effect

**Comment by invidtiv** [comment]
I was just about to come back , and say I had  a typo, thank you

**Comment by falo2k** [comment]
No worries.  It was my fat fingering in the first place!
